version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow only production dependencies to be updated
    allow:
      - dependency-type: "production"
